### ISSUE TITLE
Remote jupyter server support

### ISSUE THREAD

**Issue by JaylanLiu** [tillahoffmann/obsidian-jupyter#30]
Fantastic work!
I have been looking forward a solution to execute python code and return the result in the jupyter style for many years.
However, the data files and computing resources are usually on the hpc or the cloud server, using jupyter notebook with remote server occurs frequently.
Would this work plan to support the remote jupyter server like the VScode style?

**Comment by richukuttan** [comment]
Another use case for this would be while using Windows Subsystem for Linux - my Python interpreter's actually within the Linux subsystem. It may be possible to tweak things so that a WSL jupyter installation is possible, but I think the easier route is to simply run a jupyter server from the WSL, and connect to it via obsidian.

**Comment by tillahoffmann** [comment]
Yes, it should be possible to use this interface for remote kernels as long as there is a subprocess that adheres to the current interface (see below for details).

https://github.com/tillahoffmann/obsidian-jupyter/blob/1b7bcb5237f89c48c1fe736d27e3828080652ce2/obsidian-jupyter.py#L39-L52

However, there's of course the question of whether we should build something simply because it's possible. Existing solutions such as Jupyter Lab/Colab/etc are likely superior to this plugin for more serious development. Also see #19, #20, #22 regarding similar issues.
